services:
  app:
    build: .
    container_name: mirror_metrics
#    restart: unless-stopped
    expose:
      - 8080
    volumes:
      - ./access.log:/mirror_metrics/access.log:ro
    networks:
      - mirror

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
#    restart: unless-stopped
    expose:
     - 9090
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - mirror

networks:
  mirror:
    external: true

volumes:
  prometheus_data:
    external: true
